In [8]:
import pandas as pd

df = pd.read_csv('death.csv')

In [ ]:
df.head()

,County,FIPS,Met Objective of 45.5? (1),Age-Adjusted Death Rate,Lower 95% Confidence Interval for Death Rate,Upper 95% Confidence Interval for Death Rate,Average Deaths per Year,Recent Trend (2),Recent 5-Year Trend (2) in Death Rates,Lower 95% Confidence Interval for Trend,Upper 95% Confidence Interval for Trend
0,United States,0,No,46,45.9,46.1,"157,376",falling,-2.4,-2.6,-2.2
1,"Perry County, Kentucky",21193,No,125.6,108.9,144.2,43,stable,-0.6,-2.7,1.6
2,"Powell County, Kentucky",21197,No,125.3,100.2,155.1,18,stable,1.7,0,3.4
3,"North Slope Borough, Alaska",2185,No,124.9,73,194.7,5,**,**,**,**
4,"Owsley County, Kentucky",21189,No,118.5,83.1,165.5,8,stable,2.2,-0.4,4.8

In [10]:
df.shape

(3141, 11)

In [11]:
df.isnull().sum()

County                                          0
FIPS                                            0
Met Objective of 45.5? (1)                      0
Age-Adjusted Death Rate                         0
Lower 95% Confidence Interval for Death Rate    0
Upper 95% Confidence Interval for Death Rate    0
Average Deaths per Year                         0
Recent Trend (2)                                0
Recent 5-Year Trend (2) in Death Rates          0
Lower 95% Confidence Interval for Trend         0
Upper 95% Confidence Interval for Trend         0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3141 entries, 0 to 3140
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   County                                        3141 non-null   object
 1   FIPS                                          3141 non-null   int64
 2   Met Objective of 45.5? (1)                    3141 non-null   object
 3   Age-Adjusted Death Rate                       3141 non-null   object
 4   Lower 95% Confidence Interval for Death Rate  3141 non-null   object
 5   Upper 95% Confidence Interval for Death Rate  3141 non-null   object
 6   Average Deaths per Year                       3141 non-null   object
 7   Recent Trend (2)                              3141 non-null   object
 8   Recent 5-Year Trend (2) in Death Rates        3141 non-null   object
 9   Lower 95% Confidence Interval for Trend       3141 non-null   object
 10  Upper 95% Confidence Interval for Trend       3141 non-null   object
dtypes: int64(1), object(10)
memory usage: 270.1+ KB

In [13]:
df.describe()

               FIPS
count   3141.000000
mean   30392.281757
std    15158.200839
min        0.000000
25%    18179.000000
50%    29177.000000
75%    45081.000000
max    56045.000000